<a href="https://colab.research.google.com/github/schulzTimothy/javaScript/blob/master/scalingTwoPointPhaseRetrieval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Scaling the two-point phase-retrieval system
We'd like to measure the elements of a complex-valued field 

\begin{equation}
\underline{g} = 
\left[
  \begin{array}{c}
  g_1 \\ g_2 \\ \vdots \\ g_K
  \end{array}
\right]
=
\left[
  \begin{array}{c}
  a_1 e^{j\theta_1} \\ a_2 e^{j\theta_2} \\ \vdots \\ a_Ke^{j\theta_K}
  \end{array}
\right],
\end{equation}

that is incident on some sensing aperture. To do this, let's suppose we have a two-point phase-retrieval system that can estimate two amplitudes and a phase difference:
![picture](https://drive.google.com/uc?id=1aJ1m4sJv1wS9_comcVC2kKoOtebSU5Af)
where $\alpha$ is a scaling parameter that accounts for any splitting of the field, and the variances $\sigma^2_a(k,l)$, $\sigma^2_a(l,k)$, and $\sigma^2_{\theta}(l,k)$ are functions of the unscaled amplitudes $a_k$ and $a_l$. 

Suppose, for example, that we use this system to measure all two-point pairs for a four-element signal as shown below:
![picture](https://drive.google.com/uc?id=1TUYWcieIflPP5prJLKMpWLQs2-hAkO3P)
Because each amplitude is split three times, the scaling parameter would be $\alpha = 1/\sqrt{3}$. To estimate $a_1$, we might combine the measurements as:
\begin{align}
\widehat{a}_1 
& = \frac{1}{3 \alpha} 
\left( \widehat{a}_{1,2} + \widehat{a}_{1,3} + \widehat{a}_{1,4}\right),
\end{align}
so that
\begin{align}
E\left[ \widehat{a}_1 \right]
& = \frac{1}{3 \alpha} \left(3 \alpha a_1 \right) \nonumber \\
& = a_1,
\end{align}
and
\begin{align}
\sigma^2_{\widehat{a}_1}
& = \frac{1}{(3 \alpha)^2} \left[
\sigma_a^2(1,2) + 
\sigma_a^2(1,3) +
\sigma_a^2(1,4) 
\right] \nonumber \\
& = \frac{1}{3} \left[
\sigma_a^2(1,2) + 
\sigma_a^2(1,3) +
\sigma_a^2(1,4) 
\right].
\end{align}
Accordingly, the variance with which we estimate $a_1$ is the average of the variances with which we can estimate $a_1$ when the signal element $s_1$ is paired with each of the other signal elements. In general, then, the estimation of the amplitudes will not degrade when we increase the number of elements in the signal. 

The six measurements will obtain estimates of the following phase differences:
\begin{equation}
\begin{array}{c}
\widehat{\theta}_{2,1} \simeq \theta_2 - \theta_1 \\
\widehat{\theta}_{3,2} \simeq \theta_3 - \theta_2 \\
\widehat{\theta}_{4,3} \simeq \theta_4 - \theta_3 \\
\widehat{\theta}_{3,1} \simeq \theta_3 - \theta_1 \\
\widehat{\theta}_{4,2} \simeq \theta_4 - \theta_2 \\
\widehat{\theta}_{4,1} \simeq \theta_4 - \theta_1
\end{array}
\end{equation}

Because one of these phases is arbitrary, we could set $\theta_1 = 0$ and use the system of equations:

\begin{equation}
\left[
  \begin{array}{c}
  \widehat{\theta}_{2,1} \\
  \widehat{\theta}_{3,2} \\
  \widehat{\theta}_{4,3} \\
  \widehat{\theta}_{3,1} \\
  \widehat{\theta}_{4,2} \\
  \widehat{\theta}_{4,1} 
  \end{array}
\right]
=
\left[
  \begin{array}{ccc}
  1 & 0 & 0  \\
  -1 & 1 & 0  \\
  0 & -1 & 1  \\
  0 & 1 & 0  \\
  -1 & 0 & 1 \\
  0 & 0 & 1
  \end{array}
\right]  
\left[
  \begin{array}{c}
  \theta_2 \\ \theta_3 \\ \theta_4
  \end{array}
\right]  
\end{equation}  
to formulate our estimates for $\theta_2$, $\theta_3$, and $\theta_4$:

\begin{equation}
\left[
  \begin{array}{c}
  \widehat{\theta}_2 \\ 
  \widehat{\theta}_3 \\ 
  \widehat{\theta}_4
  \end{array}
\right] 
=
\frac{1}{4}
\left[
  \begin{array}{cccccc}
  2 & -1 & 0 & 1 & -1 & 1 \\
  1 & 1 & -1 & 2 & 0 & 1 \\
  1 & 0 & 1 & 1 & 1 & 2 
  \end{array}
\right]
\left[
  \begin{array}{c}
  \widehat{\theta}_{2,1} \\
  \widehat{\theta}_{3,2} \\
  \widehat{\theta}_{4,3} \\
  \widehat{\theta}_{3,1} \\
  \widehat{\theta}_{4,2} \\
  \widehat{\theta}_{4,1} 
  \end{array}
\right]  
\end{equation}
Then, to use $\widehat{\theta}_2$ as an example, the estimator variance will be:

\begin{align}
\sigma^2_{\widehat{\theta}_2} 
& = 
\frac{1}{16} 
\left(
  \frac{4}{\alpha^2} \sigma^2_{\theta}(2,1) + 
  \frac{1}{\alpha^2} \sigma^2_{\theta}(3,2) + 
  \frac{1}{\alpha^2} \sigma^2_{\theta}(3,1) + 
  \frac{1}{\alpha^2} \sigma^2_{\theta}(4,2) + 
  \frac{1}{\alpha^2} \sigma^2_{\theta}(4,1) + 
\right)  \nonumber \\
& \leq \frac{8}{16 \alpha^2} \mbox{max}(\sigma^2_{\theta})
\end{align}

where $\mbox{max}(\sigma^2_{\theta})$ is the maximum value for the pairwise variances used to evalute $\sigma^2_{\widehat{\theta}_2}$. Now, because $\alpha = 1/\sqrt{3}$, we have that 
\begin{equation}
\sigma^2_{\widehat{\theta}_2} \leq \frac{3}{2} \mbox{max}(\sigma^2_{\theta}).
\end{equation}
For an arbitrary number of elements $K$, the variance for the phase estimation will satisfy:
\begin{equation}
\sigma^2_{\widehat{\theta}_k} \leq \frac{2 (K-1)}{K} \mbox{max}(\sigma^2_{\theta}).
\end{equation}

(NEED TO INCLUDE SOME CODE TO SHOW THIS.)

In [0]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from scipy import linalg
from scipy.linalg import toeplitz
%matplotlib inline
plt.rcParams['figure.figsize'] = [20, 10]
np.set_printoptions(suppress=True)
np.set_printoptions(precision=3)

In [14]:
K = 6;
L = np.int_(np.round(K*(K-1)/2));
A = np.zeros((L,K));

  


print(A)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
